### ISSUE TITLE
Multiple definitions exist for class TestCase

### ISSUE THREAD

**Issue by petejohnson84** [vanderlee/PHPSwaggerGen#17]
PHPStorm gives warning "Multiple definitions exist for class TestCase" when writing unit tests for a project that has PHPSwaggerGen as a dependency. This causes autocomplete ($this->assert) to not work. I control click on TestCase and see the two definitions:

TestCase vendor/phpunit/phpunit/src/Framework
TestCase vendor/vanderlee/swaggergen/tests/bootstrap.php

It looks like bootstrap.php does some autoloading/aliasing which may be causing this. When I remove PHPSwaggerGen dependency, the warning goes away and autocomplete works.

Note that I am installing PHPUnit using this in my project composer.json

"require-dev": {
    "phpunit/phpunit": "^6.2",
}

![screen shot 2017-07-29 at 9 57 03 am](https://user-images.githubusercontent.com/16767811/28746197-c3d59020-7444-11e7-8815-37230a25c07e.png)

**Comment by vanderlee** [comment]
The alias is conditional if the class is not defined, so it's not actually an issue. PHPStorm is trying to be a little too smart for it's own good here, recognizing the `class_alias` but not the `class_exists` statements. Perhaps you could contact PHPStorm about this? They're pretty good about supporting situations like this.

The problem here is that, without the alias, the unittests won't run on all supported PHP versions. Reason for this is that different version of PHP require mutually incompatible versions of PHPUnit. Unless PHPSwaggerGen were to drop support for PHP versions 5.5 and before, I know of no other way to get PHPUnit to work without this alias.
